### ISSUE TITLE
Custom Component: prob-notebook-controller

### ISSUE THREAD

**Issue by rohank07** [StatCan/aaw-kubeflow-manifests#127]
## Overview

**EPIC**: [Kubeflow Upgrade Planning][epic-kubeflow]

| Component          | Local Manifests Path                                  | Upstream | Initial Work |
| ------------------ | ----------------------------------------------------- | -------- | ------------ |
| prob-notebook-controller | [custom/prob-notebook-controller][local-prob-notebook-controller]    | `v1.3.1` |              |

[epic-kubeflow]: https://github.com/StatCan/aaw-kubeflow-manifests/issues/110
[local-prob-notebook-controller]: https://github.com/StatCan/aaw-kubeflow-manifests/tree/main/kustomize/custom/prob-notebook-controller

**Comment by sylus** [comment]
Hey I removed the prob-notebook-controller section since i was wrong about that. That is just a custom controller that we wrote / own and is wholly separate from the kubeflow manifests and handled via Argo already.

https://github.com/StatCan/aaw-argocd-manifests/blob/aaw-dev-cc-00/daaas-system/notebook-controllers/notebook-auth-policy-checker/manifest.yaml

However when we eventually do a CI run and want to test everything it will be good to know about this component so I'm tracking in this issue:

https://github.com/StatCan/aaw-kubeflow-manifests/issues/132
